services:
  server:
    container_name: docker-lens-server
    build:
      context: .
    ports:
      - 9000:80
    develop:
      watch:
        - action: sync
          path: ./public
          target: /var/www/html/public/
        - action: sync
          path: ./src
          target: /var/www/html/src/
        - action: rebuild
          path: composer.json
        - action: rebuild
          path: composer.lock
  docs:
    container_name: docker-lens-docs
    build:
      context: ./docs
    ports:
      - 9001:80
